# Generated by Django 4.1.7 on 2023-04-07 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_name_tag_tag_alter_event_event_bullet_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='tag_name',
        ),
    ]
