# Generated by Django 4.1.7 on 2023-04-07 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_tag_tag_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_name',
            new_name='name',
        ),
    ]
