# Generated by Django 4.1.7 on 2023-04-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_event_category_excel_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='source1_image',
            field=models.URLField(blank=True, help_text='Required', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='user.tag'),
        ),
    ]
