# Generated by Django 4.1.7 on 2023-04-13 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_event_user_alter_excel_files_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='excel_files',
            old_name='user',
            new_name='author',
        ),
    ]
