# Generated by Django 4.1.7 on 2023-04-13 05:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0012_alter_event_author_alter_event_event_bullet_1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='excel_files',
            new_name='excel_file',
        ),
    ]
